config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#index'
  resources :users
  
  resources :articles do
    resources :reviews
    resources :comments do
      resources :comments
    end    
  end
  
  resources :comments do
    resources :comments
  end

  post '/likes' => 'likes#create', as: :like_create
  post '/dislikes' => 'likes#dislike', as: :dislike_create

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/comments/:id/edit' => 'comments#update'
  post '/comments/:id' => 'articles#show'

  get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/twitter/callback' => 'sessions#create'
  get '/auth/google_oauth2/callback' => 'sessions#create'

  get 'articles/:id/article_data', to: 'articles#article_data'
  get 'likes/:id/like_data', to: 'likes#like_data'
  get 'comments/:id/create', to: 'comments#create'
  post '/comments', to: 'comments#create'
  
  resources :rankings
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :author, :class_name => "User"
	belongs_to :topic
	has_many :reviews
	has_many :comments, as: :commentable, dependent: :destroy
	has_many :likes, as: :likeable, dependent: :destroy
	accepts_nested_attributes_for :topic, reject_if: :all_blank

	has_attached_file :document, :default_url => "/system/articles/documents/000/000/011/original/WITPdown.pdf"
 	validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	before_action :authenticate_user

	def index
		redirect_to root_path
	end

	def new
		@article = Article.new
	end

	def show
		@article = Article.find_by(id: params[:id])
		@comment = @article.comments.build
		@review = get_review_to_delete
		respond_to do |f|
      f.html { render :show }
      f.json { render json: @article.to_json(:include => [:author]) }
    end
	end

	def create
		@article = Article.new(article_params)
		@article.author_id = @user.id
		@article.save
		redirect_to user_path(@user)
	end

	def edit
	end

	def update
		@article = Article.find_by(id: params[:id])
		if @article.update(article_params)
			redirect_to article_path(@article)
		else
			flash.now[:notice] = "Article can not be saved, please enter information."
			render :update
		end
	end

	def destroy
		article = Article.find_by(id: params[:id])
		article.delete
		redirect_to user_path(@user)
	end

	# def body
 #    article = Article.find(params[:id])
 #    render json: ArticleSerializer.serialize(article)
 #  end

  def article_data
    article = Article.find(params[:id])
    render json: article.to_json(include: :author)
  end

	private
	def article_params
		params.require(:article).permit(:title, :author_id, :topic_id, :document, :topic_attributes => [:name])
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def available_for_review
 		Review.where("article_id = #{@article.id}" && "reviewer_id = #{@user.id}").empty?
 	end

 	def get_review_to_delete
 		Review.where("article_id = #{@article.id}" && "reviewer_id = #{@user.id}").first if @user && @article
 	end
end

app/views/articles/_form.html.erb
<%= form_for article, html: {multipart: true} do |f| %>
  <%= f.label :document %>
  <%= f.file_field :document %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <br>
  Select an existing popular topic:
  <%= f.collection_select( :topic_id, Topic.all, :id, :name, {:include_blank => 'Please Select'}) %>
  <br>
  Add a new topic:
  <%= f.fields_for :topic, article.build_topic do |topic_attributes| %> 
  <%= topic_attributes.text_field :name %>
  <% end %>

  <%= f.submit %>
<% end %><br><br>

app/views/articles/new.html.erb
Upload an Article:

<%= render partial: "form", locals: {article: @article} %>

app/views/articles/show.html.erb
<div>
	<h3>
		Title: <%= @article.title %><%= link_to "View", @article.document.url(:original, false) %><br>
		Author: <%= @article.author.first_name%> <%=@article.author.last_name %><br>
		Subject: <%= @article.topic.name %> <br>
	</h3>
</div>

<div>
<% if @user && @article.author != @user && @user.reviewer? %>
  <% if available_for_review %>  
    <%= link_to "Review this Article", article_reviews_path(@article) %>
  <% else %>
    You have already reviewed this article
    <% get_review_to_delete %> 
    <%= link_to "Delete your review?", article_review_path(@article, @review), method: :delete %>
  <% end %>
<% end %>

</div>

<div>
<% if @article.author == @user %>
Edit: 
<%= render partial: "form", locals: {article: @article} %>
<% end %> 
</div>


<br><br><br><br>

<div>


<h4>Join the Discussion</h4>
<%= render partial: "likes/like", locals: {model_obj: @article } %>
<%= render partial: 'comments/form', locals: {commentable: @article} %>



</div>