config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#index'
  resources :users
  
  resources :articles do
    resources :reviews
    resources :comments do
      resources :comments
    end    
  end
  
  resources :comments do
    resources :comments
  end

  post '/likes' => 'likes#create', as: :like_create
  post '/dislikes' => 'likes#dislike', as: :dislike_create

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/comments/:id/edit' => 'comments#update'
  post '/comments/:id' => 'articles#show'

  get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/twitter/callback' => 'sessions#create'
  get '/auth/google_oauth2/callback' => 'sessions#create'

  get 'articles/:id/article_data', to: 'articles#article_data'
  get 'likes/:id/like_data', to: 'likes#like_data'
  get 'comments/:id/create', to: 'comments#create'
  post '/comments', to: 'comments#create'
  
  resources :rankings
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
	belongs_to :user, optional: true
	belongs_to :comment, optional: true
	belongs_to :article, optional: true
 
 	def self.create_like(model, current_user)
 		like = Like.find_or_initialize_by(:likeable=>model,:user_id=>current_user.id)
 		if like.like
 			like.destroy
 		else
 			like.like= true
 		like.save
 		end
 	end
 
 	def self.create_dislike(model, current_user)
 		like = Like.find_or_initialize_by(:likeable=>model,:user_id=>current_user.id)
 		if like.like==false
 			like.destroy
 		else
 			like.like= false
 		like.save
 		end
 	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :set_model

	def create
		Like.create_like(@model, current_user)
	end
	
	def dislike
		Like.create_dislike(@model, current_user)
	end
	
	def set_model
		@model=User.find_model(params[:id], params[:type])
	end

	def like_data
		like = Like.find(params[:id])
		render json: like.to_json(:include => [:user, :likeable])
	end
end

app/views/likes/_like.html.erb
<div id="like_<%= model_obj.class.name %>_<%= model_obj.id %>">
	<!-- like -->
	<%= (count_like(model_obj)) %>
	<% if @current_user.is_liked(model_obj) %>
		<%= link_to "Liked", like_create_path(id: model_obj.id, type: model_obj.class.name), method: :post, remote: true %>
	<% else %>
		<%= link_to "Like", like_create_path(id: model_obj.id, type: model_obj.class.name), method: :post, remote: true %>
	<% end %>

	<!-- dislike -->
	<%=count_dislike(model_obj)%>
	<% if @current_user.is_disliked(model_obj) %>
		<%= link_to "Disliked", dislike_create_path(id: model_obj.id, type: model_obj.class.name), method: :post, remote: true %>
	<% else %>
		<%= link_to "Dislike", dislike_create_path(id: model_obj.id, type: model_obj.class.name), method: :post, remote: true %>
	<% end %>
</div>

app/views/likes/create.js.erb
 $("#like_<%= @model.class.name%>_<%= @model.id %>").html("<%= j(render partial: 'likes/like', locals: {model_obj: @model}) %>")

app/views/likes/dislike.js.erb
$("#like_<%= @model.class.name%>_<%= @model.id %>").html("<%= j(render partial: 'likes/like', locals: {model_obj: @model}) %>")