config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#index'
  resources :users
  
  resources :articles do
    resources :reviews
    resources :comments do
      resources :comments
    end    
  end
  
  resources :comments do
    resources :comments
  end

  post '/likes' => 'likes#create', as: :like_create
  post '/dislikes' => 'likes#dislike', as: :dislike_create

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/comments/:id/edit' => 'comments#update'
  post '/comments/:id' => 'articles#show'

  get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/twitter/callback' => 'sessions#create'
  get '/auth/google_oauth2/callback' => 'sessions#create'

  get 'articles/:id/article_data', to: 'articles#article_data'
  get 'likes/:id/like_data', to: 'likes#like_data'
  get 'comments/:id/create', to: 'comments#create'
  post '/comments', to: 'comments#create'
  
  resources :rankings
end

app/models/user.rb
class User < ApplicationRecord
	before_save :downcase_email, :format_name
  validates :username, presence: true, length: { minimum: 6, maximum: 50 }, uniqueness: true
  validates :first_name, presence: true, length: { minimum: 2, maximum: 50 } 
  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password validations: false
  validates :password, presence: true, length: { minimum: 6 }, unless: :has_uid
  has_many :articles, :foreign_key => 'author_id'
  has_many :reviews, :foreign_key => 'reviewer_id'
  has_many :topics, through: :articles
  has_many :comments

  def self.create_with_omniauth(auth)
    new_user = self.new do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"] || auth["info"]["nickname"] + "@twitter.com"
      user.username = auth["extra"]["raw_info"]["username"] || auth["info"]["nickname"] || user.email 
    end
    new_user.save
    new_user
  end

  def has_uid
    self.uid?
  end

  def most_commented_topic
    if Topic.joins(articles: :comments).joins(:users).where("user_id = #{self.id}").any?
      Topic.find(Topic.joins(articles: :comments).joins(:users).where("user_id = #{self.id}").group("topics.id").count.max_by {|topic,count| count}[0])
    end
  end

  def most_article_topic
    if Topic.joins(articles: :author).where("author_id = #{self.id}").any?
      Topic.find(Topic.joins(articles: :author).where("author_id = #{self.id}").group("topics.id").count.max_by {|topic,count| count}[0])
    end
  end

  def most_review_topic
    if Topic.joins(articles: :reviews).joins(:users).where("reviewer_id = #{self.id}").any?
      Topic.find(Topic.joins(articles: :reviews).joins(:users).where("reviewer_id = #{self.id}").group("topics.id").count.max_by {|topic,count| count}[0])
    end
  end

  def recommended_topics
    [most_article_topic, most_review_topic, most_commented_topic].uniq
  end

  def recommended_articles
    recommended_topics.map {|topic| topic.articles.where.not("author_id = #{self.id}") if topic }
  end

  def name=(name)
    names = name.split(" ")
    self.first_name = names[0]
    self.last_name = names[-1]
  end

  def name
    self.first_name + " " + self.last_name
  end

  def self.most_articles
    users = []
    User.joins(:articles).group("author_id").count.sort_by{ |k,v| v}.reverse.take(5).each do |array|
      users << array[0]
    end
    users
    User.where(id: users)
  end

  def is_liked(model)
    if Like.where(:likeable => model ,:user_id => self.id).present?
      Like.where(:likeable => model ,:user_id => self.id).last.like==true
    end
  end
 
  def is_disliked(model)
    if Like.where(:likeable => model ,:user_id => self.id).present?
      Like.where(:likeable => model ,:user_id => self.id).last.like==false
    end
  end
 
  def self.find_model(id, type)
    if type
      model = type.constantize.find(id)
      return model
    else
      model = Like.find(id).likeable_type
      return model
    end
  end

protected
	def name_format(name)
		name.downcase
		([name.split("").first.upcase] << [(name.split("").drop(1)).join("")]).join
	end

  def format_name
    self.first_name = name_format(first_name)
    self.last_name = name_format(last_name)
  end

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user, only: [:index, :show, :edit, :update]

	def index
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to user_path(@user)
		else
			flash[:notice] = "Please make sure all fields are filled before pressing submit"
			redirect_to new_user_path
		end
	end

	def show
		@article = Article.new
		if @user
			render :show
		else
			redirect_to "/signin"
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			redirect_to user_path(@user), :notice => "Successfully updated your information"
		else
			flash[:notice] = "Let's try that again"
			render :edit
		end
	end

	private
	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation, :first_name, :middle_name, :last_name, :email, :affiliation, :reviewer)
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def authenticated_login
		@user && session[:user_id] == @user.id
	end
end

app/views/users/_form.html.erb
<%= form_for user do |f| %>
    Username: <%= f.text_field :username %><br>
    Email: <%= f.text_field :email %><br>
    Password: <%= f.password_field :password %><br>
    Password Confirmation: <%= f.password_field :password_confirmation %><br>
    <br>Personal Information<br>
    First Name: <%= f.text_field :first_name %><br>
    Last Name: <%= f.text_field :last_name %><br>
    Affiliation: <%= f.text_field :affiliation %><br>
    <%= f.submit "Submit" %>
<% end %>

app/views/users/edit.html.erb
<%= render partial: "form", locals: {user: @user} %>

<%= form_for @user do |f| %>
	Do you want to be a reviewer? <%= f.check_box :reviewer, {}, "true", "false" %>
	<%= submit_tag %>
<% end %>

app/views/users/index.html.erb
Lots of great articles to checkout today:<br>
<% Article.all.each do |article| %>
	<%= link_to article.title, article_path(article) %>    |  
	<%= link_to article.author.last_name + ", " + article.author.first_name, user_path(article.author) %><br><br>
<% end %>

app/views/users/new.html.erb
<h1>Create An Account</h1>

<%= render partial: "form", locals: {user: @user} %>

app/views/users/show.html.erb
<% if authenticated_login %>

<%= link_to "Update Your Information", edit_user_path(@user) %><br>
<%= link_to "Upload an Article", new_article_path %><br>


<br>
Your Articles:
<% @user.articles.all.each do |article| %><br>
	<%= article.title %>
	<%= link_to "View", article.document.url(:original, false) %>
	<%= link_to "Go To", article_path(article) %>
	<%= link_to "Edit", edit_article_path(article) %>
	<%= link_to "Delete", article_path(article), method: :delete %>

	<% end %>
<br>
<br><br><br>

Recommended Articles:
  <% if @user.most_commented_topic || @user.most_article_topic || @user.most_review_topic %>
    <% if @user.recommended_articles[0] %>
    <% @user.recommended_articles[0].to_ary.take(20).each do |article| %><br>
        <% if article %>
          <%= article.title %>
          <%= link_to "View", article.document.url(:original, false) %>
          <%= link_to "Go To", article_path(article) %>
          <% end %>
        <% end %>
      <% end %>  
  <% end %>

<% end %>