config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#index'
  resources :users
  
  resources :articles do
    resources :reviews
    resources :comments do
      resources :comments
    end    
  end
  
  resources :comments do
    resources :comments
  end

  post '/likes' => 'likes#create', as: :like_create
  post '/dislikes' => 'likes#dislike', as: :dislike_create

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/comments/:id/edit' => 'comments#update'
  post '/comments/:id' => 'articles#show'

  get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/twitter/callback' => 'sessions#create'
  get '/auth/google_oauth2/callback' => 'sessions#create'

  get 'articles/:id/article_data', to: 'articles#article_data'
  get 'likes/:id/like_data', to: 'likes#like_data'
  get 'comments/:id/create', to: 'comments#create'
  post '/comments', to: 'comments#create'
  
  resources :rankings
end

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path %><br>
<% if @user && session[:user_id] == @user.id && @user.id != nil %>
	<%= link_to @user.first_name, user_path(@user) %><br>
	<%= link_to "Log Out", logout_path, method: :delete %><br>
<% else %>
	<%= link_to "Register", new_user_path %><br>
	<%= link_to "Sign In", login_path %><br>
	<%= link_to "Sign in with Twitter", "/auth/twitter" %>
	<%= link_to "Sign in with Facebook", "/auth/facebook" %>
	<%= link_to "Sign in with Google", "/auth/google_oauth2" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Journals Dot Com</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>

      <title>AdminLTE 2 | Starter</title>

  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  <link rel="stylesheet" href="dist/css/AdminLTE.min.css">
  
  <link rel="stylesheet" href="dist/css/skins/skin-blue.min.css">

  </head>
  <body>
    


    <%= render 'layouts/navigation' %>        
    <!-- content -->
    <div class="container"  role="main">
      <div class="center alert">
        <% flash.each do |k, v| %>
         <p><%= v %></p>
        <% end %>
      </div>
      <%= yield %>
    </div>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://momentjs.com/downloads/moment.js"></script>
    <%= javascript_include_tag "application" %>

  </body>
</html>